from typing import Any, Callable, Dict

class Heartbeat:
    def __init__(
        self,
        emit: Callable[[Dict[str, Any]], None],
        *,
        latency_ms_p95: float | None = ...,
        reconnects_total: int | None = ...
    ) -> None: ...
    def set_latency_p95(self, value: float) -> None: ...
    def set_reconnects_total(self, value: int) -> None: ...
    def tick(self, module: str, version: str) -> Dict[str, Any]: ...
