from typing import Any, Callable, Dict

class Router:
    def __init__(
        self, publisher: Any, on_error: Callable[[dict[str, Any]], None] | None = ...
    ) -> None: ...
    async def publish(
        self, topic: str, msg: dict[str, Any], compress: bool = ...
    ) -> None: ...
